all:
	gcc q1a.c -o q1a
	gcc q1b.c -o q1b -lpthread
	gcc q2a.c -o q2a
	gcc q2b.c -o q2b -lpthread
	gcc q2c.c -o q2c -lpthread
	gcc q2d1.c -o q2d1 -lpthread
	gcc q2d2.c -o q2d2 -lpthread
	gcc q2d3.c -o q2d3 -lpthread